# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_detector')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_detector')
    _detector = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_detector', [dirname(__file__)])
        except ImportError:
            import _detector
            return _detector
        try:
            _mod = imp.load_module('_detector', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _detector = swig_import_helper()
    del swig_import_helper
else:
    import _detector
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class image(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, image, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, image, name)
    __repr__ = _swig_repr
    __swig_setmethods__["h"] = _detector.image_h_set
    __swig_getmethods__["h"] = _detector.image_h_get
    if _newclass:
        h = _swig_property(_detector.image_h_get, _detector.image_h_set)
    __swig_setmethods__["w"] = _detector.image_w_set
    __swig_getmethods__["w"] = _detector.image_w_get
    if _newclass:
        w = _swig_property(_detector.image_w_get, _detector.image_w_set)
    __swig_setmethods__["c"] = _detector.image_c_set
    __swig_getmethods__["c"] = _detector.image_c_get
    if _newclass:
        c = _swig_property(_detector.image_c_get, _detector.image_c_set)
    __swig_setmethods__["data"] = _detector.image_data_set
    __swig_getmethods__["data"] = _detector.image_data_get
    if _newclass:
        data = _swig_property(_detector.image_data_get, _detector.image_data_set)

    def __init__(self):
        this = _detector.new_image()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _detector.delete_image
    __del__ = lambda self: None
image_swigregister = _detector.image_swigregister
image_swigregister(image)

LOGISTIC = _detector.LOGISTIC
RELU = _detector.RELU
RELIE = _detector.RELIE
LINEAR = _detector.LINEAR
RAMP = _detector.RAMP
TANH = _detector.TANH
PLSE = _detector.PLSE
LEAKY = _detector.LEAKY
ELU = _detector.ELU
LOGGY = _detector.LOGGY
STAIR = _detector.STAIR
HARDTAN = _detector.HARDTAN
LHTAN = _detector.LHTAN

def get_activation(s):
    return _detector.get_activation(s)
get_activation = _detector.get_activation

def get_color(c, x, max):
    return _detector.get_color(c, x, max)
get_color = _detector.get_color

def flip_image(a):
    return _detector.flip_image(a)
flip_image = _detector.flip_image

def draw_box(a, x1, y1, x2, y2, r, g, b):
    return _detector.draw_box(a, x1, y1, x2, y2, r, g, b)
draw_box = _detector.draw_box

def draw_box_width(a, x1, y1, x2, y2, w, r, g, b):
    return _detector.draw_box_width(a, x1, y1, x2, y2, w, r, g, b)
draw_box_width = _detector.draw_box_width

def draw_bbox(a, bbox, w, r, g, b):
    return _detector.draw_bbox(a, bbox, w, r, g, b)
draw_bbox = _detector.draw_bbox

def draw_label(a, r, c, label, rgb):
    return _detector.draw_label(a, r, c, label, rgb)
draw_label = _detector.draw_label

def draw_detections(im, num, thresh, boxes, probs, names, labels, classes):
    return _detector.draw_detections(im, num, thresh, boxes, probs, names, labels, classes)
draw_detections = _detector.draw_detections

def image_distance(a, b):
    return _detector.image_distance(a, b)
image_distance = _detector.image_distance

def scale_image(m, s):
    return _detector.scale_image(m, s)
scale_image = _detector.scale_image

def crop_image(im, dx, dy, w, h):
    return _detector.crop_image(im, dx, dy, w, h)
crop_image = _detector.crop_image

def random_crop_image(im, w, h):
    return _detector.random_crop_image(im, w, h)
random_crop_image = _detector.random_crop_image

def random_augment_image(im, angle, aspect, low, high, size):
    return _detector.random_augment_image(im, angle, aspect, low, high, size)
random_augment_image = _detector.random_augment_image

def random_distort_image(im, hue, saturation, exposure):
    return _detector.random_distort_image(im, hue, saturation, exposure)
random_distort_image = _detector.random_distort_image

def resize_image(im, w, h):
    return _detector.resize_image(im, w, h)
resize_image = _detector.resize_image

def resize_min(im, min):
    return _detector.resize_min(im, min)
resize_min = _detector.resize_min

def resize_max(im, max):
    return _detector.resize_max(im, max)
resize_max = _detector.resize_max

def translate_image(m, s):
    return _detector.translate_image(m, s)
translate_image = _detector.translate_image

def normalize_image(p):
    return _detector.normalize_image(p)
normalize_image = _detector.normalize_image

def rotate_image(m, rad):
    return _detector.rotate_image(m, rad)
rotate_image = _detector.rotate_image

def rotate_image_cw(im, times):
    return _detector.rotate_image_cw(im, times)
rotate_image_cw = _detector.rotate_image_cw

def embed_image(source, dest, dx, dy):
    return _detector.embed_image(source, dest, dx, dy)
embed_image = _detector.embed_image

def saturate_image(im, sat):
    return _detector.saturate_image(im, sat)
saturate_image = _detector.saturate_image

def exposure_image(im, sat):
    return _detector.exposure_image(im, sat)
exposure_image = _detector.exposure_image

def distort_image(im, hue, sat, val):
    return _detector.distort_image(im, hue, sat, val)
distort_image = _detector.distort_image

def saturate_exposure_image(im, sat, exposure):
    return _detector.saturate_exposure_image(im, sat, exposure)
saturate_exposure_image = _detector.saturate_exposure_image

def hsv_to_rgb(im):
    return _detector.hsv_to_rgb(im)
hsv_to_rgb = _detector.hsv_to_rgb

def rgbgr_image(im):
    return _detector.rgbgr_image(im)
rgbgr_image = _detector.rgbgr_image

def constrain_image(im):
    return _detector.constrain_image(im)
constrain_image = _detector.constrain_image

def composite_3d(f1, f2, out, delta):
    return _detector.composite_3d(f1, f2, out, delta)
composite_3d = _detector.composite_3d

def best_3d_shift_r(a, b, min, max):
    return _detector.best_3d_shift_r(a, b, min, max)
best_3d_shift_r = _detector.best_3d_shift_r

def grayscale_image(im):
    return _detector.grayscale_image(im)
grayscale_image = _detector.grayscale_image

def threshold_image(im, thresh):
    return _detector.threshold_image(im, thresh)
threshold_image = _detector.threshold_image

def collapse_image_layers(source, border):
    return _detector.collapse_image_layers(source, border)
collapse_image_layers = _detector.collapse_image_layers

def collapse_images_horz(ims, n):
    return _detector.collapse_images_horz(ims, n)
collapse_images_horz = _detector.collapse_images_horz

def collapse_images_vert(ims, n):
    return _detector.collapse_images_vert(ims, n)
collapse_images_vert = _detector.collapse_images_vert

def show_image(p, name):
    return _detector.show_image(p, name)
show_image = _detector.show_image

def show_image_normalized(im, name):
    return _detector.show_image_normalized(im, name)
show_image_normalized = _detector.show_image_normalized

def save_image_png(im, name):
    return _detector.save_image_png(im, name)
save_image_png = _detector.save_image_png

def save_image(p, name):
    return _detector.save_image(p, name)
save_image = _detector.save_image

def show_images(ims, n, window):
    return _detector.show_images(ims, n, window)
show_images = _detector.show_images

def show_image_layers(p, name):
    return _detector.show_image_layers(p, name)
show_image_layers = _detector.show_image_layers

def show_image_collapsed(p, name):
    return _detector.show_image_collapsed(p, name)
show_image_collapsed = _detector.show_image_collapsed

def print_image(m):
    return _detector.print_image(m)
print_image = _detector.print_image

def make_image(w, h, c):
    return _detector.make_image(w, h, c)
make_image = _detector.make_image

def make_random_image(w, h, c):
    return _detector.make_random_image(w, h, c)
make_random_image = _detector.make_random_image

def make_empty_image(w, h, c):
    return _detector.make_empty_image(w, h, c)
make_empty_image = _detector.make_empty_image

def float_to_image(w, h, c, data):
    return _detector.float_to_image(w, h, c, data)
float_to_image = _detector.float_to_image

def copy_image(p):
    return _detector.copy_image(p)
copy_image = _detector.copy_image

def load_image(filename, w, h, c):
    return _detector.load_image(filename, w, h, c)
load_image = _detector.load_image

def load_image_color(filename, w, h):
    return _detector.load_image_color(filename, w, h)
load_image_color = _detector.load_image_color

def load_alphabet():
    return _detector.load_alphabet()
load_alphabet = _detector.load_alphabet

def get_pixel(m, x, y, c):
    return _detector.get_pixel(m, x, y, c)
get_pixel = _detector.get_pixel

def get_pixel_extend(m, x, y, c):
    return _detector.get_pixel_extend(m, x, y, c)
get_pixel_extend = _detector.get_pixel_extend

def set_pixel(m, x, y, c, val):
    return _detector.set_pixel(m, x, y, c, val)
set_pixel = _detector.set_pixel

def add_pixel(m, x, y, c, val):
    return _detector.add_pixel(m, x, y, c, val)
add_pixel = _detector.add_pixel

def bilinear_interpolate(im, x, y, c):
    return _detector.bilinear_interpolate(im, x, y, c)
bilinear_interpolate = _detector.bilinear_interpolate

def get_image_layer(m, l):
    return _detector.get_image_layer(m, l)
get_image_layer = _detector.get_image_layer

def free_image(m):
    return _detector.free_image(m)
free_image = _detector.free_image

def test_resize(filename):
    return _detector.test_resize(filename)
test_resize = _detector.test_resize
class box(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, box, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, box, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _detector.box_x_set
    __swig_getmethods__["x"] = _detector.box_x_get
    if _newclass:
        x = _swig_property(_detector.box_x_get, _detector.box_x_set)
    __swig_setmethods__["y"] = _detector.box_y_set
    __swig_getmethods__["y"] = _detector.box_y_get
    if _newclass:
        y = _swig_property(_detector.box_y_get, _detector.box_y_set)
    __swig_setmethods__["w"] = _detector.box_w_set
    __swig_getmethods__["w"] = _detector.box_w_get
    if _newclass:
        w = _swig_property(_detector.box_w_get, _detector.box_w_set)
    __swig_setmethods__["h"] = _detector.box_h_set
    __swig_getmethods__["h"] = _detector.box_h_get
    if _newclass:
        h = _swig_property(_detector.box_h_get, _detector.box_h_set)

    def __init__(self):
        this = _detector.new_box()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _detector.delete_box
    __del__ = lambda self: None
box_swigregister = _detector.box_swigregister
box_swigregister(box)

class dbox(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, dbox, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, dbox, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dx"] = _detector.dbox_dx_set
    __swig_getmethods__["dx"] = _detector.dbox_dx_get
    if _newclass:
        dx = _swig_property(_detector.dbox_dx_get, _detector.dbox_dx_set)
    __swig_setmethods__["dy"] = _detector.dbox_dy_set
    __swig_getmethods__["dy"] = _detector.dbox_dy_get
    if _newclass:
        dy = _swig_property(_detector.dbox_dy_get, _detector.dbox_dy_set)
    __swig_setmethods__["dw"] = _detector.dbox_dw_set
    __swig_getmethods__["dw"] = _detector.dbox_dw_get
    if _newclass:
        dw = _swig_property(_detector.dbox_dw_get, _detector.dbox_dw_set)
    __swig_setmethods__["dh"] = _detector.dbox_dh_set
    __swig_getmethods__["dh"] = _detector.dbox_dh_get
    if _newclass:
        dh = _swig_property(_detector.dbox_dh_get, _detector.dbox_dh_set)

    def __init__(self):
        this = _detector.new_dbox()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _detector.delete_dbox
    __del__ = lambda self: None
dbox_swigregister = _detector.dbox_swigregister
dbox_swigregister(dbox)


def float_to_box(f):
    return _detector.float_to_box(f)
float_to_box = _detector.float_to_box

def box_iou(a, b):
    return _detector.box_iou(a, b)
box_iou = _detector.box_iou

def box_rmse(a, b):
    return _detector.box_rmse(a, b)
box_rmse = _detector.box_rmse

def diou(a, b):
    return _detector.diou(a, b)
diou = _detector.diou

def do_nms(boxes, probs, total, classes, thresh):
    return _detector.do_nms(boxes, probs, total, classes, thresh)
do_nms = _detector.do_nms

def do_nms_sort(boxes, probs, total, classes, thresh):
    return _detector.do_nms_sort(boxes, probs, total, classes, thresh)
do_nms_sort = _detector.do_nms_sort

def do_nms_obj(boxes, probs, total, classes, thresh):
    return _detector.do_nms_obj(boxes, probs, total, classes, thresh)
do_nms_obj = _detector.do_nms_obj

def decode_box(b, anchor):
    return _detector.decode_box(b, anchor)
decode_box = _detector.decode_box

def encode_box(b, anchor):
    return _detector.encode_box(b, anchor)
encode_box = _detector.encode_box

def read_map(filename):
    return _detector.read_map(filename)
read_map = _detector.read_map

def shuffle(arr, n, size):
    return _detector.shuffle(arr, n, size)
shuffle = _detector.shuffle

def sorta_shuffle(arr, n, size, sections):
    return _detector.sorta_shuffle(arr, n, size, sections)
sorta_shuffle = _detector.sorta_shuffle

def free_ptrs(ptrs, n):
    return _detector.free_ptrs(ptrs, n)
free_ptrs = _detector.free_ptrs

def basecfg(cfgfile):
    return _detector.basecfg(cfgfile)
basecfg = _detector.basecfg

def alphanum_to_int(c):
    return _detector.alphanum_to_int(c)
alphanum_to_int = _detector.alphanum_to_int

def int_to_alphanum(i):
    return _detector.int_to_alphanum(i)
int_to_alphanum = _detector.int_to_alphanum

def read_int(fd):
    return _detector.read_int(fd)
read_int = _detector.read_int

def write_int(fd, n):
    return _detector.write_int(fd, n)
write_int = _detector.write_int

def read_all(fd, buffer, bytes):
    return _detector.read_all(fd, buffer, bytes)
read_all = _detector.read_all

def write_all(fd, buffer, bytes):
    return _detector.write_all(fd, buffer, bytes)
write_all = _detector.write_all

def read_all_fail(fd, buffer, bytes):
    return _detector.read_all_fail(fd, buffer, bytes)
read_all_fail = _detector.read_all_fail

def write_all_fail(fd, buffer, bytes):
    return _detector.write_all_fail(fd, buffer, bytes)
write_all_fail = _detector.write_all_fail

def find_replace(str, orig, rep, output):
    return _detector.find_replace(str, orig, rep, output)
find_replace = _detector.find_replace

def error(s):
    return _detector.error(s)
error = _detector.error

def malloc_error():
    return _detector.malloc_error()
malloc_error = _detector.malloc_error

def file_error(s):
    return _detector.file_error(s)
file_error = _detector.file_error

def strip(s):
    return _detector.strip(s)
strip = _detector.strip

def strip_char(s, bad):
    return _detector.strip_char(s, bad)
strip_char = _detector.strip_char

def top_k(a, n, k, index):
    return _detector.top_k(a, n, k, index)
top_k = _detector.top_k

def split_str(s, delim):
    return _detector.split_str(s, delim)
split_str = _detector.split_str

def fgetl(fp):
    return _detector.fgetl(fp)
fgetl = _detector.fgetl

def parse_csv_line(line):
    return _detector.parse_csv_line(line)
parse_csv_line = _detector.parse_csv_line

def copy_string(s):
    return _detector.copy_string(s)
copy_string = _detector.copy_string

def count_fields(line):
    return _detector.count_fields(line)
count_fields = _detector.count_fields

def parse_fields(line, n):
    return _detector.parse_fields(line, n)
parse_fields = _detector.parse_fields

def normalize_array(a, n):
    return _detector.normalize_array(a, n)
normalize_array = _detector.normalize_array

def scale_array(a, n, s):
    return _detector.scale_array(a, n, s)
scale_array = _detector.scale_array

def translate_array(a, n, s):
    return _detector.translate_array(a, n, s)
translate_array = _detector.translate_array

def max_index(a, n):
    return _detector.max_index(a, n)
max_index = _detector.max_index

def constrain(min, max, a):
    return _detector.constrain(min, max, a)
constrain = _detector.constrain

def constrain_int(a, min, max):
    return _detector.constrain_int(a, min, max)
constrain_int = _detector.constrain_int

def mse_array(a, n):
    return _detector.mse_array(a, n)
mse_array = _detector.mse_array

def rand_normal():
    return _detector.rand_normal()
rand_normal = _detector.rand_normal

def rand_size_t():
    return _detector.rand_size_t()
rand_size_t = _detector.rand_size_t

def rand_uniform(min, max):
    return _detector.rand_uniform(min, max)
rand_uniform = _detector.rand_uniform

def rand_scale(s):
    return _detector.rand_scale(s)
rand_scale = _detector.rand_scale

def rand_int(min, max):
    return _detector.rand_int(min, max)
rand_int = _detector.rand_int

def sum_array(a, n):
    return _detector.sum_array(a, n)
sum_array = _detector.sum_array

def mean_array(a, n):
    return _detector.mean_array(a, n)
mean_array = _detector.mean_array

def mean_arrays(a, n, els, avg):
    return _detector.mean_arrays(a, n, els, avg)
mean_arrays = _detector.mean_arrays

def variance_array(a, n):
    return _detector.variance_array(a, n)
variance_array = _detector.variance_array

def mag_array(a, n):
    return _detector.mag_array(a, n)
mag_array = _detector.mag_array

def dist_array(a, b, n, sub):
    return _detector.dist_array(a, b, n, sub)
dist_array = _detector.dist_array

def one_hot_encode(a, n, k):
    return _detector.one_hot_encode(a, n, k)
one_hot_encode = _detector.one_hot_encode

def sec(clocks):
    return _detector.sec(clocks)
sec = _detector.sec

def find_int_arg(argc, argv, arg, arg4):
    return _detector.find_int_arg(argc, argv, arg, arg4)
find_int_arg = _detector.find_int_arg

def find_float_arg(argc, argv, arg, arg4):
    return _detector.find_float_arg(argc, argv, arg, arg4)
find_float_arg = _detector.find_float_arg

def find_arg(argc, argv, arg):
    return _detector.find_arg(argc, argv, arg)
find_arg = _detector.find_arg

def find_char_arg(argc, argv, arg, arg4):
    return _detector.find_char_arg(argc, argv, arg, arg4)
find_char_arg = _detector.find_char_arg

def sample_array(a, n):
    return _detector.sample_array(a, n)
sample_array = _detector.sample_array

def print_statistics(a, n):
    return _detector.print_statistics(a, n)
print_statistics = _detector.print_statistics
class node(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, node, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, node, name)
    __repr__ = _swig_repr
    __swig_setmethods__["val"] = _detector.node_val_set
    __swig_getmethods__["val"] = _detector.node_val_get
    if _newclass:
        val = _swig_property(_detector.node_val_get, _detector.node_val_set)
    __swig_setmethods__["next"] = _detector.node_next_set
    __swig_getmethods__["next"] = _detector.node_next_get
    if _newclass:
        next = _swig_property(_detector.node_next_get, _detector.node_next_set)
    __swig_setmethods__["prev"] = _detector.node_prev_set
    __swig_getmethods__["prev"] = _detector.node_prev_get
    if _newclass:
        prev = _swig_property(_detector.node_prev_get, _detector.node_prev_set)

    def __init__(self):
        this = _detector.new_node()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _detector.delete_node
    __del__ = lambda self: None
node_swigregister = _detector.node_swigregister
node_swigregister(node)

class list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, list, name)
    __repr__ = _swig_repr
    __swig_setmethods__["size"] = _detector.list_size_set
    __swig_getmethods__["size"] = _detector.list_size_get
    if _newclass:
        size = _swig_property(_detector.list_size_get, _detector.list_size_set)
    __swig_setmethods__["front"] = _detector.list_front_set
    __swig_getmethods__["front"] = _detector.list_front_get
    if _newclass:
        front = _swig_property(_detector.list_front_get, _detector.list_front_set)
    __swig_setmethods__["back"] = _detector.list_back_set
    __swig_getmethods__["back"] = _detector.list_back_get
    if _newclass:
        back = _swig_property(_detector.list_back_get, _detector.list_back_set)

    def __init__(self):
        this = _detector.new_list()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _detector.delete_list
    __del__ = lambda self: None
list_swigregister = _detector.list_swigregister
list_swigregister(list)


def make_list():
    return _detector.make_list()
make_list = _detector.make_list

def list_insert(arg1, arg2):
    return _detector.list_insert(arg1, arg2)
list_insert = _detector.list_insert

def list_to_array(l):
    return _detector.list_to_array(l)
list_to_array = _detector.list_to_array

def free_list(l):
    return _detector.free_list(l)
free_list = _detector.free_list

def free_list_contents(l):
    return _detector.free_list_contents(l)
free_list_contents = _detector.free_list_contents

def smooth_l1_cpu(n, pred, truth, delta, error):
    return _detector.smooth_l1_cpu(n, pred, truth, delta, error)
smooth_l1_cpu = _detector.smooth_l1_cpu

def l2_cpu(n, pred, truth, delta, error):
    return _detector.l2_cpu(n, pred, truth, delta, error)
l2_cpu = _detector.l2_cpu

def softmax(input, n, temp, output):
    return _detector.softmax(input, n, temp, output)
softmax = _detector.softmax

def dot_cpu(N, X, INCX, Y, INCY):
    return _detector.dot_cpu(N, X, INCX, Y, INCY)
dot_cpu = _detector.dot_cpu

def copy_cpu(N, X, INCX, Y, INCY):
    return _detector.copy_cpu(N, X, INCX, Y, INCY)
copy_cpu = _detector.copy_cpu

def fill_cpu(N, ALPHA, X, INCX):
    return _detector.fill_cpu(N, ALPHA, X, INCX)
fill_cpu = _detector.fill_cpu

def scal_cpu(N, ALPHA, X, INCX):
    return _detector.scal_cpu(N, ALPHA, X, INCX)
scal_cpu = _detector.scal_cpu

def const_cpu(N, ALPHA, X, INCX):
    return _detector.const_cpu(N, ALPHA, X, INCX)
const_cpu = _detector.const_cpu

def pow_cpu(N, ALPHA, X, INCX, Y, INCY):
    return _detector.pow_cpu(N, ALPHA, X, INCX, Y, INCY)
pow_cpu = _detector.pow_cpu

def mul_cpu(N, X, INCX, Y, INCY):
    return _detector.mul_cpu(N, X, INCX, Y, INCY)
mul_cpu = _detector.mul_cpu

def axpy_cpu(N, ALPHA, X, INCX, Y, INCY):
    return _detector.axpy_cpu(N, ALPHA, X, INCX, Y, INCY)
axpy_cpu = _detector.axpy_cpu

def mean_cpu(x, batch, filters, spatial, mean):
    return _detector.mean_cpu(x, batch, filters, spatial, mean)
mean_cpu = _detector.mean_cpu

def variance_cpu(x, mean, batch, filters, spatial, variance):
    return _detector.variance_cpu(x, mean, batch, filters, spatial, variance)
variance_cpu = _detector.variance_cpu

def normalize_cpu(x, mean, variance, batch, filters, spatial):
    return _detector.normalize_cpu(x, mean, variance, batch, filters, spatial)
normalize_cpu = _detector.normalize_cpu

def flatten(x, size, layers, batch, forward):
    return _detector.flatten(x, size, layers, batch, forward)
flatten = _detector.flatten

def reorg_cpu(x, w, h, c, batch, stride, forward, out):
    return _detector.reorg_cpu(x, w, h, c, batch, stride, forward, out)
reorg_cpu = _detector.reorg_cpu

def shortcut_cpu(batch, w1, h1, c1, add, w2, h2, c2, out):
    return _detector.shortcut_cpu(batch, w1, h1, c1, add, w2, h2, c2, out)
shortcut_cpu = _detector.shortcut_cpu

def test_detector(datacfg, cfgfile, weightfile, filename, thresh, hier_thresh):
    return _detector.test_detector(datacfg, cfgfile, weightfile, filename, thresh, hier_thresh)
test_detector = _detector.test_detector

def demo(cfgfile, weightfile, thresh, cam_index, filename, names, classes, frame_skip, prefix, hier_thresh):
    return _detector.demo(cfgfile, weightfile, thresh, cam_index, filename, names, classes, frame_skip, prefix, hier_thresh)
demo = _detector.demo

def free_data(d):
    return _detector.free_data(d)
free_data = _detector.free_data
class matrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, matrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, matrix, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rows"] = _detector.matrix_rows_set
    __swig_getmethods__["rows"] = _detector.matrix_rows_get
    if _newclass:
        rows = _swig_property(_detector.matrix_rows_get, _detector.matrix_rows_set)
    __swig_setmethods__["cols"] = _detector.matrix_cols_set
    __swig_getmethods__["cols"] = _detector.matrix_cols_get
    if _newclass:
        cols = _swig_property(_detector.matrix_cols_get, _detector.matrix_cols_set)
    __swig_setmethods__["vals"] = _detector.matrix_vals_set
    __swig_getmethods__["vals"] = _detector.matrix_vals_get
    if _newclass:
        vals = _swig_property(_detector.matrix_vals_get, _detector.matrix_vals_set)

    def __init__(self):
        this = _detector.new_matrix()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _detector.delete_matrix
    __del__ = lambda self: None
matrix_swigregister = _detector.matrix_swigregister
matrix_swigregister(matrix)


def csv_to_matrix(filename):
    return _detector.csv_to_matrix(filename)
csv_to_matrix = _detector.csv_to_matrix

def get_current_batch(net):
    return _detector.get_current_batch(net)
get_current_batch = _detector.get_current_batch

def free_layer(arg1):
    return _detector.free_layer(arg1)
free_layer = _detector.free_layer

def get_region_boxes(l, w, h, thresh, probs, boxes, only_objectness, map, tree_thresh):
    return _detector.get_region_boxes(l, w, h, thresh, probs, boxes, only_objectness, map, tree_thresh)
get_region_boxes = _detector.get_region_boxes

def get_hierarchy_probability(x, hier, c):
    return _detector.get_hierarchy_probability(x, hier, c)
get_hierarchy_probability = _detector.get_hierarchy_probability

def load_weights(net, filename):
    return _detector.load_weights(net, filename)
load_weights = _detector.load_weights
class network(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, network, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, network, name)
    __repr__ = _swig_repr
    __swig_setmethods__["workspace"] = _detector.network_workspace_set
    __swig_getmethods__["workspace"] = _detector.network_workspace_get
    if _newclass:
        workspace = _swig_property(_detector.network_workspace_get, _detector.network_workspace_set)
    __swig_setmethods__["n"] = _detector.network_n_set
    __swig_getmethods__["n"] = _detector.network_n_get
    if _newclass:
        n = _swig_property(_detector.network_n_get, _detector.network_n_set)
    __swig_setmethods__["batch"] = _detector.network_batch_set
    __swig_getmethods__["batch"] = _detector.network_batch_get
    if _newclass:
        batch = _swig_property(_detector.network_batch_get, _detector.network_batch_set)
    __swig_setmethods__["seen"] = _detector.network_seen_set
    __swig_getmethods__["seen"] = _detector.network_seen_get
    if _newclass:
        seen = _swig_property(_detector.network_seen_get, _detector.network_seen_set)
    __swig_setmethods__["epoch"] = _detector.network_epoch_set
    __swig_getmethods__["epoch"] = _detector.network_epoch_get
    if _newclass:
        epoch = _swig_property(_detector.network_epoch_get, _detector.network_epoch_set)
    __swig_setmethods__["subdivisions"] = _detector.network_subdivisions_set
    __swig_getmethods__["subdivisions"] = _detector.network_subdivisions_get
    if _newclass:
        subdivisions = _swig_property(_detector.network_subdivisions_get, _detector.network_subdivisions_set)
    __swig_setmethods__["momentum"] = _detector.network_momentum_set
    __swig_getmethods__["momentum"] = _detector.network_momentum_get
    if _newclass:
        momentum = _swig_property(_detector.network_momentum_get, _detector.network_momentum_set)
    __swig_setmethods__["decay"] = _detector.network_decay_set
    __swig_getmethods__["decay"] = _detector.network_decay_get
    if _newclass:
        decay = _swig_property(_detector.network_decay_get, _detector.network_decay_set)
    __swig_setmethods__["layers"] = _detector.network_layers_set
    __swig_getmethods__["layers"] = _detector.network_layers_get
    if _newclass:
        layers = _swig_property(_detector.network_layers_get, _detector.network_layers_set)
    __swig_setmethods__["outputs"] = _detector.network_outputs_set
    __swig_getmethods__["outputs"] = _detector.network_outputs_get
    if _newclass:
        outputs = _swig_property(_detector.network_outputs_get, _detector.network_outputs_set)
    __swig_setmethods__["output"] = _detector.network_output_set
    __swig_getmethods__["output"] = _detector.network_output_get
    if _newclass:
        output = _swig_property(_detector.network_output_get, _detector.network_output_set)
    __swig_setmethods__["policy"] = _detector.network_policy_set
    __swig_getmethods__["policy"] = _detector.network_policy_get
    if _newclass:
        policy = _swig_property(_detector.network_policy_get, _detector.network_policy_set)
    __swig_setmethods__["learning_rate"] = _detector.network_learning_rate_set
    __swig_getmethods__["learning_rate"] = _detector.network_learning_rate_get
    if _newclass:
        learning_rate = _swig_property(_detector.network_learning_rate_get, _detector.network_learning_rate_set)
    __swig_setmethods__["gamma"] = _detector.network_gamma_set
    __swig_getmethods__["gamma"] = _detector.network_gamma_get
    if _newclass:
        gamma = _swig_property(_detector.network_gamma_get, _detector.network_gamma_set)
    __swig_setmethods__["scale"] = _detector.network_scale_set
    __swig_getmethods__["scale"] = _detector.network_scale_get
    if _newclass:
        scale = _swig_property(_detector.network_scale_get, _detector.network_scale_set)
    __swig_setmethods__["power"] = _detector.network_power_set
    __swig_getmethods__["power"] = _detector.network_power_get
    if _newclass:
        power = _swig_property(_detector.network_power_get, _detector.network_power_set)
    __swig_setmethods__["time_steps"] = _detector.network_time_steps_set
    __swig_getmethods__["time_steps"] = _detector.network_time_steps_get
    if _newclass:
        time_steps = _swig_property(_detector.network_time_steps_get, _detector.network_time_steps_set)
    __swig_setmethods__["step"] = _detector.network_step_set
    __swig_getmethods__["step"] = _detector.network_step_get
    if _newclass:
        step = _swig_property(_detector.network_step_get, _detector.network_step_set)
    __swig_setmethods__["max_batches"] = _detector.network_max_batches_set
    __swig_getmethods__["max_batches"] = _detector.network_max_batches_get
    if _newclass:
        max_batches = _swig_property(_detector.network_max_batches_get, _detector.network_max_batches_set)
    __swig_setmethods__["scales"] = _detector.network_scales_set
    __swig_getmethods__["scales"] = _detector.network_scales_get
    if _newclass:
        scales = _swig_property(_detector.network_scales_get, _detector.network_scales_set)
    __swig_setmethods__["steps"] = _detector.network_steps_set
    __swig_getmethods__["steps"] = _detector.network_steps_get
    if _newclass:
        steps = _swig_property(_detector.network_steps_get, _detector.network_steps_set)
    __swig_setmethods__["num_steps"] = _detector.network_num_steps_set
    __swig_getmethods__["num_steps"] = _detector.network_num_steps_get
    if _newclass:
        num_steps = _swig_property(_detector.network_num_steps_get, _detector.network_num_steps_set)
    __swig_setmethods__["burn_in"] = _detector.network_burn_in_set
    __swig_getmethods__["burn_in"] = _detector.network_burn_in_get
    if _newclass:
        burn_in = _swig_property(_detector.network_burn_in_get, _detector.network_burn_in_set)
    __swig_setmethods__["adam"] = _detector.network_adam_set
    __swig_getmethods__["adam"] = _detector.network_adam_get
    if _newclass:
        adam = _swig_property(_detector.network_adam_get, _detector.network_adam_set)
    __swig_setmethods__["B1"] = _detector.network_B1_set
    __swig_getmethods__["B1"] = _detector.network_B1_get
    if _newclass:
        B1 = _swig_property(_detector.network_B1_get, _detector.network_B1_set)
    __swig_setmethods__["B2"] = _detector.network_B2_set
    __swig_getmethods__["B2"] = _detector.network_B2_get
    if _newclass:
        B2 = _swig_property(_detector.network_B2_get, _detector.network_B2_set)
    __swig_setmethods__["eps"] = _detector.network_eps_set
    __swig_getmethods__["eps"] = _detector.network_eps_get
    if _newclass:
        eps = _swig_property(_detector.network_eps_get, _detector.network_eps_set)
    __swig_setmethods__["inputs"] = _detector.network_inputs_set
    __swig_getmethods__["inputs"] = _detector.network_inputs_get
    if _newclass:
        inputs = _swig_property(_detector.network_inputs_get, _detector.network_inputs_set)
    __swig_setmethods__["h"] = _detector.network_h_set
    __swig_getmethods__["h"] = _detector.network_h_get
    if _newclass:
        h = _swig_property(_detector.network_h_get, _detector.network_h_set)
    __swig_setmethods__["w"] = _detector.network_w_set
    __swig_getmethods__["w"] = _detector.network_w_get
    if _newclass:
        w = _swig_property(_detector.network_w_get, _detector.network_w_set)
    __swig_setmethods__["c"] = _detector.network_c_set
    __swig_getmethods__["c"] = _detector.network_c_get
    if _newclass:
        c = _swig_property(_detector.network_c_get, _detector.network_c_set)
    __swig_setmethods__["max_crop"] = _detector.network_max_crop_set
    __swig_getmethods__["max_crop"] = _detector.network_max_crop_get
    if _newclass:
        max_crop = _swig_property(_detector.network_max_crop_get, _detector.network_max_crop_set)
    __swig_setmethods__["min_crop"] = _detector.network_min_crop_set
    __swig_getmethods__["min_crop"] = _detector.network_min_crop_get
    if _newclass:
        min_crop = _swig_property(_detector.network_min_crop_get, _detector.network_min_crop_set)
    __swig_setmethods__["angle"] = _detector.network_angle_set
    __swig_getmethods__["angle"] = _detector.network_angle_get
    if _newclass:
        angle = _swig_property(_detector.network_angle_get, _detector.network_angle_set)
    __swig_setmethods__["aspect"] = _detector.network_aspect_set
    __swig_getmethods__["aspect"] = _detector.network_aspect_get
    if _newclass:
        aspect = _swig_property(_detector.network_aspect_get, _detector.network_aspect_set)
    __swig_setmethods__["exposure"] = _detector.network_exposure_set
    __swig_getmethods__["exposure"] = _detector.network_exposure_get
    if _newclass:
        exposure = _swig_property(_detector.network_exposure_get, _detector.network_exposure_set)
    __swig_setmethods__["saturation"] = _detector.network_saturation_set
    __swig_getmethods__["saturation"] = _detector.network_saturation_get
    if _newclass:
        saturation = _swig_property(_detector.network_saturation_get, _detector.network_saturation_set)
    __swig_setmethods__["hue"] = _detector.network_hue_set
    __swig_getmethods__["hue"] = _detector.network_hue_get
    if _newclass:
        hue = _swig_property(_detector.network_hue_get, _detector.network_hue_set)
    __swig_setmethods__["gpu_index"] = _detector.network_gpu_index_set
    __swig_getmethods__["gpu_index"] = _detector.network_gpu_index_get
    if _newclass:
        gpu_index = _swig_property(_detector.network_gpu_index_get, _detector.network_gpu_index_set)
    __swig_setmethods__["hierarchy"] = _detector.network_hierarchy_set
    __swig_getmethods__["hierarchy"] = _detector.network_hierarchy_get
    if _newclass:
        hierarchy = _swig_property(_detector.network_hierarchy_get, _detector.network_hierarchy_set)

    def __init__(self):
        this = _detector.new_network()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _detector.delete_network
    __del__ = lambda self: None
network_swigregister = _detector.network_swigregister
network_swigregister(network)


def get_cost_type(s):
    return _detector.get_cost_type(s)
get_cost_type = _detector.get_cost_type

def make_activation_layer(batch, inputs, activation):
    return _detector.make_activation_layer(batch, inputs, activation)
make_activation_layer = _detector.make_activation_layer

def make_avgpool_layer(batch, w, h, c):
    return _detector.make_avgpool_layer(batch, w, h, c)
make_avgpool_layer = _detector.make_avgpool_layer

def make_batchnorm_layer(batch, w, h, c):
    return _detector.make_batchnorm_layer(batch, w, h, c)
make_batchnorm_layer = _detector.make_batchnorm_layer

def make_connected_layer(batch, inputs, outputs, activation, batch_normalize):
    return _detector.make_connected_layer(batch, inputs, outputs, activation, batch_normalize)
make_connected_layer = _detector.make_connected_layer

def gemm(TA, TB, M, N, K, ALPHA, A, lda, B, ldb, BETA, C, ldc):
    return _detector.gemm(TA, TB, M, N, K, ALPHA, A, lda, B, ldb, BETA, C, ldc)
gemm = _detector.gemm

def make_convolutional_layer(batch, h, w, c, n, size, stride, padding, activation, batch_normalize, binary, xnor, adam):
    return _detector.make_convolutional_layer(batch, h, w, c, n, size, stride, padding, activation, batch_normalize, binary, xnor, adam)
make_convolutional_layer = _detector.make_convolutional_layer

def make_crnn_layer(batch, h, w, c, hidden_filters, output_filters, steps, activation, batch_normalize):
    return _detector.make_crnn_layer(batch, h, w, c, hidden_filters, output_filters, steps, activation, batch_normalize)
make_crnn_layer = _detector.make_crnn_layer

def make_crop_layer(batch, h, w, c, crop_height, crop_width, flip, angle, saturation, exposure):
    return _detector.make_crop_layer(batch, h, w, c, crop_height, crop_width, flip, angle, saturation, exposure)
make_crop_layer = _detector.make_crop_layer

def make_detection_layer(batch, inputs, n, size, classes, coords, rescore):
    return _detector.make_detection_layer(batch, inputs, n, size, classes, coords, rescore)
make_detection_layer = _detector.make_detection_layer

def make_dropout_layer(batch, inputs, probability):
    return _detector.make_dropout_layer(batch, inputs, probability)
make_dropout_layer = _detector.make_dropout_layer

def make_normalization_layer(batch, w, h, c, size, alpha, beta, kappa):
    return _detector.make_normalization_layer(batch, w, h, c, size, alpha, beta, kappa)
make_normalization_layer = _detector.make_normalization_layer

def make_shortcut_layer(batch, index, w, h, c, w2, h2, c2):
    return _detector.make_shortcut_layer(batch, index, w, h, c, w2, h2, c2)
make_shortcut_layer = _detector.make_shortcut_layer

def make_route_layer(batch, n, input_layers, input_size):
    return _detector.make_route_layer(batch, n, input_layers, input_size)
make_route_layer = _detector.make_route_layer

def make_gru_layer(batch, inputs, outputs, steps, batch_normalize):
    return _detector.make_gru_layer(batch, inputs, outputs, steps, batch_normalize)
make_gru_layer = _detector.make_gru_layer

def make_softmax_layer(batch, inputs, groups):
    return _detector.make_softmax_layer(batch, inputs, groups)
make_softmax_layer = _detector.make_softmax_layer

def make_maxpool_layer(batch, h, w, c, size, stride, padding):
    return _detector.make_maxpool_layer(batch, h, w, c, size, stride, padding)
make_maxpool_layer = _detector.make_maxpool_layer

def make_reorg_layer(batch, h, w, c, stride, reverse):
    return _detector.make_reorg_layer(batch, h, w, c, stride, reverse)
make_reorg_layer = _detector.make_reorg_layer

def make_local_layer(batch, h, w, c, n, size, stride, pad, activation):
    return _detector.make_local_layer(batch, h, w, c, n, size, stride, pad, activation)
make_local_layer = _detector.make_local_layer

def make_rnn_layer(batch, inputs, hidden, outputs, steps, activation, batch_normalize, log):
    return _detector.make_rnn_layer(batch, inputs, hidden, outputs, steps, activation, batch_normalize, log)
make_rnn_layer = _detector.make_rnn_layer

def option_find(l, key):
    return _detector.option_find(l, key)
option_find = _detector.option_find

def option_find_str(l, key, arg3):
    return _detector.option_find_str(l, key, arg3)
option_find_str = _detector.option_find_str

def option_find_int(l, key, arg3):
    return _detector.option_find_int(l, key, arg3)
option_find_int = _detector.option_find_int

def option_find_int_quiet(l, key, arg3):
    return _detector.option_find_int_quiet(l, key, arg3)
option_find_int_quiet = _detector.option_find_int_quiet

def option_find_float(l, key, arg3):
    return _detector.option_find_float(l, key, arg3)
option_find_float = _detector.option_find_float

def option_find_float_quiet(l, key, arg3):
    return _detector.option_find_float_quiet(l, key, arg3)
option_find_float_quiet = _detector.option_find_float_quiet

def save_weights(net, filename):
    return _detector.save_weights(net, filename)
save_weights = _detector.save_weights

def col2im_cpu(data_col, channels, height, width, ksize, stride, pad, data_im):
    return _detector.col2im_cpu(data_col, channels, height, width, ksize, stride, pad, data_im)
col2im_cpu = _detector.col2im_cpu

def im2col_cpu(data_im, channels, height, width, ksize, stride, pad, data_col):
    return _detector.im2col_cpu(data_im, channels, height, width, ksize, stride, pad, data_col)
im2col_cpu = _detector.im2col_cpu
# This file is compatible with both classic and new-style classes.


